Miscellaneous tweaks
pret/pokegold pull request #72
Opened 2022-01-08 23:18 UTC by FrenchOrange

*Removed the unused IDs for the Schoolboy class. The file "Parties.asm" has no corresponding data for those, and it looks like neither do the final games.

*Changed "BUG_CATCHER_BENNY" to just "BENNY" for the sake of uniformisation.
 
*Changed the first two IDs for the Super Nerd class, so that they match "Parties.asm".

*Added a mention to a seemingly unused trainer (initial encounter - Super Nerd Eric).

2022-01-08 23:25 UTC, Rangi42 commented on constants/trainer_constants.asm
> +	const ERIC2
`ERIC2` is used in GoldenrodUnderground; please change these to `ERIC_UNUSED` and `ERIC`, like Crystal's `NAOKO_UNUSED` and `NAOKO`.

2022-01-08 23:28 UTC, mid-kid commented
Thanks a lot for your contribution! The suggestions seem fine, though I'd keep `BUG_CATCHER_BENNY` for uniformity with crystal - that has a `BIKER_BENNY` as well. In any circumstance the constants names should reflect the strings in the ROM.

2022-01-09 00:05 UTC, Rangi42 commented
I'm fine with the change to `BENNY`. There are other changes made to omit knowledge from Crystal, like renaming some `GSFuncName` functions to just `FuncName`, or `ENGINE_SWARM` vs `ENGINE_FISH_SWARM`.

2022-01-26 17:35 UTC, Rangi42 commented
This does not build: the code still uses the old `BUG_CATCHER_BENNY` name.

2022-03-07 19:39 UTC, Rangi42 requested changes
`Unknown symbol "SuperNerdEricUnusedBattleText"`

Make sure that `make compare` works.

2022-03-07 20:00 UTC, vulcandth commented
@FrenchOrange It looks like your making your changes directly on github.com. The ideal way to update a PR is to checkout your branch [FrenchOrange:patch-1 ](https://github.com/FrenchOrange/pokegold/tree/patch-1) on your local computer. Do your changes, run `make compare` to verify that your changes build successfully, and then finally you git push a commit with your changes to your local branch. The PR will automatically update with any changes made to your local branch that your are attempting to pull into the main repo.

2022-03-07 23:15 UTC, Rangi42 approved these changes

2022-03-08 01:49 UTC, merged